export { Home } from './Home'
export { ThisWeek } from './ThisWeek'
export { AboutGame } from './AboutGame'
export { LastDays } from './LastDays'
export { NextWeek } from './NextWeek'
export { AboutGenre } from './AboutGenre'
export { Browse } from './Browse'
export { Common } from './Common'
