export { Home } from './Home'
export { ThisWeek } from './ThisWeek'
export { AboutGame } from './AboutGame'
export { LastDays } from './LastDays'
export { NextWeek } from './NextWeek'
export { GanresPage } from './GanresPage'
